# See the link below for the sample config file for livekit:
# https://github.com/livekit/livekit/blob/master/config-sample.yaml

port: 7880
log_level: info

redis:
  address: localhost:6379
  password: antimony
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000

  # Enable if deploying to cloud environments
  use_external_ip: false
keys:
  key1: secret1
